---
title: "436 hw 2"
output: html_document
date: "2023-03-13"
---
```{r, echo = F, warning=F, message = F,results="hide"}
library(sf)
library(ggplot2)
library(dplyr)
library(plotly)
library("tsibbledata")
library("lubridate")
library(feasts)
library(tsibble)
library(shiny)
library(tidyverse)
library(shinythemes)
library(car)
```


```{r, echo = F}
df = read.csv("https://uwmadison.box.com/shared/static/jqlmp13ac36mrkzdondccrh8hd24rk8w.csv")
df$Date = df$Date %>% as.Date(format = "%m/%d/%Y")
df1 = df%>%
  drop_na()
df2 = df%>%
  mutate(month = month(Date))
lm1 = glm(as.factor(Arrest)~Domestic+as.factor(Community.Area)+as.factor(month)+
            as.factor(Primary.Type),data = df2,family = binomial())
```




```{r, fig.height=8, fig.width=8, echo = F}
chicago_geom <- read_sf('https://uwmadison.box.com/shared/static/i92uvz0le30zzo2k7wb9qui4f7s4yvkf.geojson')
df$Month = as.integer(substr(df$Date, 1, 2))
df$Date = df$Date %>% as.Date(format = "%m/%d/%Y")
time_df = df %>% 
  group_by(Date) %>%
  summarise(count = n(),arrest_number = sum(Arrest =="true"))%>%
  mutate(prob = arrest_number/count)
time_df = as_tsibble(time_df, index = Date)
time_df = fill_gaps(time_df, .full = FALSE)
cols = scales::viridis_pal()(10)
```





```{r}
df3=df2 %>%
      mutate(arrest_prob = predict(object = lm1,newdata = df2, type = "response"))%>%
      select(arrest_prob,Arrest,Domestic,Community.Area,month,Primary.Type)
```




```{r, eval = FALSE, echo = F}
ui<-fluidPage(
  theme = shinythemes::shinytheme('superhero'),
  titlePanel("Chicago Crime"),
  verbatimTextOutput("brush_info"),
  sidebarLayout(
    sidebarPanel(
titlePanel("Customize barplot for visualizing count for different crimes in the selected region"),
       helpText("Select community number to visualize count for different crimes in this region"),
       selectInput("Community", 
                  label = "Choose Community.Area",
                  choices = seq(1,77,1),
                  selected = "1"),
titlePanel("Customize barplot and map plot"),
        helpText("Below selection pannels are used for customize the barplot and map plot. To customize the visualization, select a time period and the level of time. The map plot will demonstrate the arrested probability, and the barplot will demonstrate the total arrested number by each community area"),
   sliderInput("Month",
               label = "Select a month",
               min = 1, max = 12, value = c(1, 12)),
   helpText("Time Series Plot that visualize the arrest probability as time moves in 2021."),
         titlePanel("Time Series"),
   helpText("choose a level of time, then the time series will be constructed by this time period"),
   selectInput("Date",
               label = "Choose a variable to display",
               choices = c("year",
                           "month"),
               selected = "year")
    ),
    mainPanel(
      plotOutput("bar_plot1"),
      plotOutput("map_plot"),
      plotOutput("bar_plot"),
      plotOutput("ts_plot"),
      textOutput("brush")
    )
  ),
   fluidRow(
  column(4, plotOutput("histogram", brush = brushOpts("plot_brush", direction = "x"))) ),
  dataTableOutput("table")
  )


server <- function(input, output) {
     output$bar_plot1 <- renderPlot({
     df2%>%
    filter(Community.Area ==input$Community)%>%
  group_by(Primary.Type)%>%
  summarise(n = n())%>%
  ggplot()+geom_bar(aes(n, reorder(Primary.Type, n),fill = n), width = 0.8, stat = "identity")+theme_bw() + labs(x = "count", y = "Crime type", fill = "n")+ggtitle("Crime Count by Each type of crime ")
    })
  
    output$ts_plot <- renderPlot({

      gg_season(time_df, prob, period = input$Date, pal = cols) + 
        theme_bw()+ggtitle("Time Series Plot for crime probability by selected time period")
    })
    
    output$map_plot <- renderPlot({
      arr = df2 %>% filter( (as.integer(month) >= input$Month[1]) & (as.integer(month) <= input$Month[2])) %>% 
        group_by(Community.Area) %>% 
        summarise(count = n(),arrest_number = sum(Arrest == "true"))%>%mutate(prob = arrest_number/count)
      chicago_geom$area_num_1 = as.integer(chicago_geom$area_num_1)
      chicago_geom %>% left_join(arr, by = c("area_num_1" = "Community.Area"))%>% 
        ggplot() + 
          geom_sf(size = 0.2, color = "black", aes(fill = prob)) + 
          ggtitle("Battery Crime arrest probability  Plot") + 
          coord_sf() + 
          scale_fill_viridis_c(option = "magma",begin = 0.1) + 
          theme_bw()+ggtitle("map plot with displayed arrested probability for selected time period ")
    })
    output$bar_plot <- renderPlot({
        count = df2 %>% filter( (as.integer(month) >= input$Month[1]) & (as.integer(month) <= input$Month[2])) %>% 
          group_by(Community.Area) %>% 
          summarise(count = n(),arrest_number = sum(Arrest == "true"))%>%
          arrange(., desc(arrest_number)) 
        count[1:10,] %>% ggplot() + 
          geom_bar(aes(arrest_number, reorder(Community.Area, arrest_number), fill = arrest_number), width = 0.8, stat = "identity") + 
          theme_bw() + 
          scale_x_continuous(expand = c(0,0)) + 
          labs(x = "Arrest Number", y = "Community Area")+ggtitle("Crime Count by Each Community Area Within the Selected Time Period")
      
    })    
    output$brush<- renderText({
    "Below histogram display the count for crimes for each region. You can interact with this histogram by brushing some data. It will display a table contains all brushed entries with their arrest probability, crime domestic status, crime type, community area, and month. Probability are calculated based on logistics regression, fitted with month, domestic status(labeled as Domestic in data), crime type(labled as Primary.Type), and community area."
  })
  histogram_selection <- reactiveVal(rep(TRUE, nrow(df2)))
observeEvent(
    input$plot_brush, {
     new_values <- brushedPoints(df2, input$plot_brush, allRows = TRUE)$selected_
      histogram_selection(new_values)
    }
  )      

 output$histogram <- renderPlot({
    ggplot(df2) +
      geom_histogram(aes(Community.Area)) 
  })
  
  output$table <- renderDataTable({
    df3 %>%
      filter(histogram_selection() )
})
}
app <- shinyApp(ui, server)
app
```